-- CreateTable
CREATE TABLE `Tour` (
    `id` VARCHAR(191) NOT NULL,
    `slug` VARCHAR(191) NOT NULL,
    `status` ENUM('DRAFT', 'PUBLISHED') NOT NULL DEFAULT 'PUBLISHED',
    `order` INTEGER NOT NULL DEFAULT 0,
    `duration_vi` VARCHAR(191) NOT NULL,
    `duration_en` VARCHAR(191) NOT NULL,
    `name_vi` VARCHAR(191) NOT NULL,
    `name_en` VARCHAR(191) NOT NULL,
    `subtitle_vi` TEXT NOT NULL,
    `subtitle_en` TEXT NOT NULL,
    `destination_vi` VARCHAR(191) NOT NULL,
    `destination_en` VARCHAR(191) NOT NULL,
    `price_vi` VARCHAR(191) NOT NULL,
    `price_en` VARCHAR(191) NOT NULL,
    `groupSize_vi` VARCHAR(191) NOT NULL,
    `groupSize_en` VARCHAR(191) NOT NULL,
    `certificate_vi` TEXT NOT NULL,
    `certificate_en` TEXT NOT NULL,
    `whyJoin_vi` TEXT NOT NULL,
    `whyJoin_en` TEXT NOT NULL,
    `customization_vi` TEXT NOT NULL,
    `customization_en` TEXT NOT NULL,
    `highlights_vi` JSON NOT NULL,
    `highlights_en` JSON NOT NULL,
    `audience_vi` JSON NOT NULL,
    `audience_en` JSON NOT NULL,
    `itinerary_vi` JSON NOT NULL,
    `itinerary_en` JSON NOT NULL,
    `includes_vi` JSON NOT NULL,
    `includes_en` JSON NOT NULL,
    `excludes_vi` JSON NOT NULL,
    `excludes_en` JSON NOT NULL,
    `gallery_vi` JSON NOT NULL,
    `gallery_en` JSON NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `Tour_slug_key`(`slug`),
    INDEX `Tour_status_idx`(`status`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
